# uminho is split into two sets because it is the longest chain
# and the compilation would have to wait for this chain to finish
[order: lang, doctype, school; processor: lua]
uminho/eaad		[phd, msc]  [en]
uminho/ec		[phd, msc]  [en]
uminho/ed		[phd, msc]  [en]
uminho/eeg		[phd, msc]  [en]
uminho/eeng		[phd, msc]  [en]
uminho/elach	[phd, msc]  [en]
uminho/emed		[phd, msc]  [en]
uminho/epsi		[phd, msc]  [en]
uminho/ese		[phd, msc]  [en]
uminho/i3bs		[phd, msc]  [en]
uminho/ics		[phd, msc]  [en]
uminho/ie		[phd, msc]  [en]

[order: lang, doctype, school; processor: lua]
uminho/eaad		[phd, msc]  [pt]
uminho/ec		[phd, msc]  [pt]
uminho/ed		[phd, msc]  [pt]
uminho/eeg		[phd, msc]  [pt]
uminho/eeng		[phd, msc]  [pt]
uminho/elach	[phd, msc]  [pt]
uminho/emed		[phd, msc]  [pt]
uminho/epsi		[phd, msc]  [pt]
uminho/ese		[phd, msc]  [pt]
uminho/i3bs		[phd, msc]  [pt]
uminho/ics		[phd, msc]  [pt]
uminho/ie		[phd, msc]  [pt]

[order: school, lang, doctype; processor: pdf,lua]
ips/ests		[msc]  [en,pt]

[order: school, lang, doctype; processor: lua]
ipl/isel		[msc]  [en,pt]
ipl/isel/meb	[msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
iscteiul/eta	[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
nova/ensp		[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
nova/fcsh		[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
nova/fct		[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
nova/fct/cbbi	[msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
nova/fct/di-adc	[bsc]  [en,pt]

[order: lang, doctype, school; processor: pdf,lua]
nova/itqb/gray	[phd, msc]  [en,pt]
nova/itqb/green	[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: lua]
other/esep		[msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
ulht/deisi		[phd, msc]  [en,pt]
ulht/mge		[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
ulisboa/fcul	[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: lua]
ulisboa/fmv		[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
ulisboa/iseg	[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
ulisboa/ist		[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
ulisboa/fful	[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: pdf,lua]
uporto/fcup		[phd, msc]  [en,pt]

[order: school, lang, doctype; processor: lua]
other/novathesis		[phd]  [en,pt]
